name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: devops
      DB_NAME: devopsdb
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Ckeckout repository
        uses: actions/checkout@v4
      - name: Start services
        working-directory: ./compose-microservices
        run: |
          docker compose up -d --build
          echo "=== CONTAINERS==="
          docker compose ps
          echo " === POSTGRESS LOGS =="
          docker compose logs postgres
      - name: Run test
        working-directory: ./compose-microservices
        run: docker compose exec -T backend npm test
      - name: Stop services
        if: always()
        working-directory: ./compose-microservices
        run: docker compose down
      - name: Show Docker version
        run: docker --version

